apiVersion: v1
kind: Service
metadata:
  name: notebook
spec:
  selector:
    app: notebook
  ports:
    - port: {{ .Values.notebook.service.port }}
      targetPort: {{ .Values.notebook.service.port }}
  type: NodePort
